name: Github Pages
on:
  push:
    branches:
      - master
  schedule:
    # Run this script every 1 hrs
    #  */m hr day month day_of_week
    - cron:  '0 */1 * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Description Tag'  
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: run
        run: |
          npm install --omit=dev
          npm run build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v3
        with:
          branch: gh-pages 
          folder: dist
